

////BaseEarning Actions
export const GET_BASEEARNINGS_ALL = 'GET_BASEEARNINGS_ALL';
export const GET_BASEEARNING = 'GET_BASEEARNING';
export const UPDATE_EARNING_LIST = 'UPDATE_EARNING_LIST';
export const CREATE_EARNING_LIST = 'CREATE_EARNING_LIST';
export const GET_BASEEARNINGS_SELECTED = 'GET_BASEEARNINGS_SELECTED';
export const UPDATE_OTHERFLAG = 'UPDATE_OTHERFLAG';
export const UPDATE_SELECTED_EARNINGS = 'UPDATE_SELECTED_EARNINGS';
export const UPDATE_OTHER_STRING = 'UPDATE_OTHER_STRING';


//AccuralPlans Actions

export const GET_ACCURALPLANS_ALL = 'GET_ACCURALPLANS_ALL';
export const GET_ACCURALPLAN = 'GET_ACCURALPLAN';
export const UPDATE_PLAN_LIST = 'UPDATE_PLAN_LIST';
export const CREATE_PLAN_LIST = 'CREATE_PLAN_LIST';
export const GET_ACCURALPLANS_SELECTED = 'GET_ACCURALPLANS_SELECTED';
export const HAVE_ACCURAL_PLAN = 'HAVE_ACCURAL_PLAN';



//Tips Actions

export const GET_TIPS_ALL = 'GET_TIPS_ALL';
export const GET_TIP = 'GET_TIP';
export const UPDATE_TIP_LIST = 'UPDATE_TIP_LIST';
export const CREATE_TIP_LIST = 'CREATE_TIP_LIST';
export const GET_TIPS_SELECTED = 'GET_TIPS_SELECTED';
export const IS_TIPPED_EMPLOYEE = 'IS_TIPPED_EMPLOYEE';









